name: "golang: Release & publish"
description: GitHub Action that produces a new Release of a golang based repository.
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    description: GitHub token that can checkout the consumer repository as well as create tags/releases against it. e.g. 'secrets.GITHUB_TOKEN'
    required: true
outputs:
  version:
    description: Version of the project
    value: ${{ steps.release.outputs.version }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Authorize
      uses: open-turo/action-git-auth@v2
      with:
        github-personal-access-token: ${{ inputs.github-token }}
    - name: Setup tools
      ## Installs version of golang found in .go-version
      uses: open-turo/action-setup-tools@v1
    - name: Semantic release
      uses: go-semantic-release/action@v1
      id: release
      with:
        github-token: ${{ inputs.github-token }}
    - name: Fetch tags
      shell: bash
      run: |
        git fetch --tags
        git clean -fd
    - name: Set Go Version
      shell: bash
      run: |
        echo "GOVERSION=$(< .go-version tr -d '\n')" >> $GITHUB_ENV
    - name: Goreleaser
      uses: goreleaser/goreleaser-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GOPRIVATE: github.com/turo/
      with:
        args: release
